<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TSkqa9LService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.tSkqa9L' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tSkqa9L'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'storeFilters' => ['privates', '.errored..service_locator.tSkqa9L.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\StoreFilters', NULL, 'Cannot autowire service ".service_locator.tSkqa9L": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\StoreFilters" but no such service exists.'],
        ], [
            'storeFilters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\StoreFilters',
        ]);
    }
}
