<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gl1WsZService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator._Gl1WsZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._Gl1WsZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'disabledProductFilters' => ['privates', '.errored..service_locator._Gl1WsZ.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\Monitoring\\DisabledProductFilters', NULL, 'Cannot autowire service ".service_locator._Gl1WsZ": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\Monitoring\\DisabledProductFilters" but no such service exists.'],
            'emptyCategoryFilters' => ['privates', '.errored..service_locator._Gl1WsZ.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\Monitoring\\EmptyCategoryFilters', NULL, 'Cannot autowire service ".service_locator._Gl1WsZ": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\Monitoring\\EmptyCategoryFilters" but no such service exists.'],
            'noQtyProductWithCombinationFilters' => ['privates', '.errored..service_locator._Gl1WsZ.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\Monitoring\\NoQtyProductWithCombinationFilters', NULL, 'Cannot autowire service ".service_locator._Gl1WsZ": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\Monitoring\\NoQtyProductWithCombinationFilters" but no such service exists.'],
            'noQtyProductWithoutCombinationFilters' => ['privates', '.errored..service_locator._Gl1WsZ.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\Monitoring\\NoQtyProductWithoutCombinationFilters', NULL, 'Cannot autowire service ".service_locator._Gl1WsZ": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\Monitoring\\NoQtyProductWithoutCombinationFilters" but no such service exists.'],
            'productWithoutDescriptionFilters' => ['privates', '.errored..service_locator._Gl1WsZ.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\Monitoring\\ProductWithoutDescriptionFilters', NULL, 'Cannot autowire service ".service_locator._Gl1WsZ": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\Monitoring\\ProductWithoutDescriptionFilters" but no such service exists.'],
            'productWithoutImageFilters' => ['privates', '.errored..service_locator._Gl1WsZ.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\Monitoring\\ProductWithoutImageFilters', NULL, 'Cannot autowire service ".service_locator._Gl1WsZ": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\Monitoring\\ProductWithoutImageFilters" but no such service exists.'],
            'productWithoutPriceFilters' => ['privates', '.errored..service_locator._Gl1WsZ.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\Monitoring\\ProductWithoutPriceFilters', NULL, 'Cannot autowire service ".service_locator._Gl1WsZ": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\Monitoring\\ProductWithoutPriceFilters" but no such service exists.'],
        ], [
            'disabledProductFilters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\Monitoring\\DisabledProductFilters',
            'emptyCategoryFilters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\Monitoring\\EmptyCategoryFilters',
            'noQtyProductWithCombinationFilters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\Monitoring\\NoQtyProductWithCombinationFilters',
            'noQtyProductWithoutCombinationFilters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\Monitoring\\NoQtyProductWithoutCombinationFilters',
            'productWithoutDescriptionFilters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\Monitoring\\ProductWithoutDescriptionFilters',
            'productWithoutImageFilters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\Monitoring\\ProductWithoutImageFilters',
            'productWithoutPriceFilters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\Monitoring\\ProductWithoutPriceFilters',
        ]);
    }
}
