<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_GHSQEOsService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.GHSQEOs' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.GHSQEOs'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor((new \PrestaShop\PrestaShop\Core\Domain\ImageSettings\CommandHandler\RegenerateThumbnailsHandler(($container->services['translator'] ?? self::getTranslatorService($container)), ($container->services['PrestaShopBundle\\Entity\\Repository\\ImageTypeRepository'] ?? $container->load('getImageTypeRepositoryService')), ($container->services['prestashop.core.admin.lang.repository'] ?? self::getPrestashop_Core_Admin_Lang_RepositoryService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\ImageThumbnailsRegenerator'] ?? $container->load('getImageThumbnailsRegeneratorService'))))->handle(...), ['method' => 'handle']);
    }
}
