<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7nY1oyGService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.7nY1oyG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7nY1oyG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'attributeGroupFilters' => ['privates', '.errored..service_locator.7nY1oyG.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\AttributeGroupFilters', NULL, 'Cannot autowire service ".service_locator.7nY1oyG": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\AttributeGroupFilters" but no such service exists.'],
        ], [
            'attributeGroupFilters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\AttributeGroupFilters',
        ]);
    }
}
