<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Container_Private_Prestashop_Bundle_Grid_ResponseBuilderService extends AdminKernelProdContainer
{
    /*
     * Gets the public '.container.private.prestashop.bundle.grid.response_builder' shared service.
     *
     * @return \PrestaShopBundle\Service\Grid\ResponseBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['.container.private.prestashop.bundle.grid.response_builder'] = new \PrestaShopBundle\Service\Grid\ResponseBuilder(($container->services['prestashop.core.grid.filter.form_factory'] ?? $container->load('getPrestashop_Core_Grid_Filter_FormFactoryService')), ($container->services['prestashop.router'] ?? $container->load('getPrestashop_RouterService')), ($container->services['prestashop.core.admin.admin_filter.repository'] ?? $container->load('getPrestashop_Core_Admin_AdminFilter_RepositoryService')), ($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container))->getContext()->employee->id, ($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container))->getContext()->shop->id, ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
