<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MZbFnJgService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.MZbFnJg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MZbFnJg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'orderReturnStatesFilters' => ['privates', '.errored..service_locator.MZbFnJg.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\OrderReturnStatesFilters', NULL, 'Cannot autowire service ".service_locator.MZbFnJg": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\OrderReturnStatesFilters" but no such service exists.'],
            'orderStatesFilters' => ['privates', '.errored..service_locator.MZbFnJg.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\OrderStatesFilters', NULL, 'Cannot autowire service ".service_locator.MZbFnJg": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\OrderStatesFilters" but no such service exists.'],
        ], [
            'orderReturnStatesFilters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\OrderReturnStatesFilters',
            'orderStatesFilters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\OrderStatesFilters',
        ]);
    }
}
