<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Container_Private_Prestashop_Bundle_Twig_Extension_JsRouterMetadataExtensionService extends AdminKernelProdContainer
{
    /*
     * Gets the public '.container.private.prestashop.bundle.twig.extension.js_router_metadata_extension' shared autowired service.
     *
     * @return \PrestaShopBundle\Twig\Extension\JsRouterMetadataExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['security.helper'] ?? self::getSecurity_HelperService($container));

        if (isset($container->services['.container.private.prestashop.bundle.twig.extension.js_router_metadata_extension'])) {
            return $container->services['.container.private.prestashop.bundle.twig.extension.js_router_metadata_extension'];
        }

        return $container->services['.container.private.prestashop.bundle.twig.extension.js_router_metadata_extension'] = new \PrestaShopBundle\Twig\Extension\JsRouterMetadataExtension(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['Symfony\\Component\\Security\\Csrf\\CsrfTokenManagerInterface'] ?? self::getCsrfTokenManagerInterfaceService($container)), $a);
    }
}
