<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TJeBCYTService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.TJeBCYT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TJeBCYT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'configuration' => ['services', 'PrestaShop\\PrestaShop\\Adapter\\Configuration', 'getConfigurationService', false],
        ], [
            'configuration' => '?',
        ]);
    }
}
