<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Container_Private_Prestashop_Bundle_Twig_Extension_MultistoreUrlService extends AdminKernelProdContainer
{
    /*
     * Gets the public '.container.private.prestashop.bundle.twig.extension.multistore_url' shared autowired service.
     *
     * @return \PrestaShopBundle\Twig\Extension\MultistoreUrlExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['.container.private.prestashop.bundle.twig.extension.multistore_url'] = new \PrestaShopBundle\Twig\Extension\MultistoreUrlExtension(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
