<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9NXoZs2Service extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.9NXoZs2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9NXoZs2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'filters' => ['privates', '.errored..service_locator.9NXoZs2.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CustomerThreadFilter', NULL, 'Cannot autowire service ".service_locator.9NXoZs2": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CustomerThreadFilter" but no such service exists.'],
        ], [
            'filters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CustomerThreadFilter',
        ]);
    }
}
