<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WVB_LFTService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.wVB.LFT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wVB.LFT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'manufacturerAddressFilters' => ['privates', '.errored..service_locator.wVB.LFT.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ManufacturerAddressFilters', NULL, 'Cannot autowire service ".service_locator.wVB.LFT": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ManufacturerAddressFilters" but no such service exists.'],
            'manufacturerFilters' => ['privates', '.errored..service_locator.wVB.LFT.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ManufacturerFilters', NULL, 'Cannot autowire service ".service_locator.wVB.LFT": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ManufacturerFilters" but no such service exists.'],
        ], [
            'manufacturerAddressFilters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ManufacturerAddressFilters',
            'manufacturerFilters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ManufacturerFilters',
        ]);
    }
}
