<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Container_Private_Prestashop_MultistoreCheckboxEnablerService extends AdminKernelProdContainer
{
    /*
     * Gets the public '.container.private.prestashop.multistore_checkbox_enabler' shared autowired service.
     *
     * @return \PrestaShopBundle\Service\Form\MultistoreCheckboxEnabler
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['prestashop.core.admin.multistore'] ?? $container->load('getPrestashop_Core_Admin_MultistoreService'));

        if (isset($container->services['.container.private.prestashop.multistore_checkbox_enabler'])) {
            return $container->services['.container.private.prestashop.multistore_checkbox_enabler'];
        }

        return $container->services['.container.private.prestashop.multistore_checkbox_enabler'] = new \PrestaShopBundle\Service\Form\MultistoreCheckboxEnabler(($container->services['PrestaShop\\PrestaShop\\Adapter\\Feature\\MultistoreFeature'] ?? self::getMultistoreFeatureService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration()), ($container->services['.container.private.prestashop.adapter.shop.context'] ??= new \PrestaShop\PrestaShop\Adapter\Shop\Context()), $a, ($container->privates['PrestaShopBundle\\Form\\FormCloner'] ??= new \PrestaShopBundle\Form\FormCloner()));
    }
}
