<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAttributeFiltersService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.R3qk0ro.PrestaShop\PrestaShop\Core\Search\Filters\AttributeFilters' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Search\Filters\AttributeFilters
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.R3qk0ro": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\AttributeFilters" but no such service exists.');
    }
}
