<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiClientContextService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShop\PrestaShop\Core\Context\ApiClientContext' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Core\Context\ApiClientContext
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['PrestaShop\\PrestaShop\\Core\\Context\\ApiClientContext'] = $container->createProxy('ApiClientContextProxy4b23c09', static fn () => \ApiClientContextProxy4b23c09::createLazyProxy(static fn () => self::do($container, false)));
        }

        return (new \PrestaShop\PrestaShop\Core\Context\ApiClientContextBuilder(($container->services['PrestaShopBundle\\Entity\\Repository\\ApiClientRepository'] ?? $container->load('getApiClientRepositoryService')), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration())))->build();
    }
}
