<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackupInterfaceService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShop\PrestaShop\Core\Backup\BackupInterface' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Backup\DatabaseBackupCreator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShop\\PrestaShop\\Core\\Backup\\BackupInterface'] = new \PrestaShop\PrestaShop\Adapter\Backup\DatabaseBackupCreator();
    }
}
