<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCmsPageCategoryFiltersService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator..y.p6p7.PrestaShop\PrestaShop\Core\Search\Filters\CmsPageCategoryFilters' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Search\Filters\CmsPageCategoryFilters
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..y.p6p7": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CmsPageCategoryFilters" but no such service exists.');
    }
}
