<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCountryContextService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShop\PrestaShop\Core\Context\CountryContext' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Core\Context\CountryContext
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['PrestaShop\\PrestaShop\\Core\\Context\\CountryContext'] = $container->createProxy('CountryContextProxy089af55', static fn () => \CountryContextProxy089af55::createLazyProxy(static fn () => self::do($container, false)));
        }

        return ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\CountryContextBuilder'] ?? self::getCountryContextBuilderService($container))->build();
    }
}
