<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandProcessorService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopBundle\ApiPlatform\Processor\CommandProcessor' shared autowired service.
     *
     * @return \PrestaShopBundle\ApiPlatform\Processor\CommandProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['prestashop.core.command_bus'] ?? $container->load('getPrestashop_Core_CommandBusService'));

        if (isset($container->privates['PrestaShopBundle\\ApiPlatform\\Processor\\CommandProcessor'])) {
            return $container->privates['PrestaShopBundle\\ApiPlatform\\Processor\\CommandProcessor'];
        }

        return $container->privates['PrestaShopBundle\\ApiPlatform\\Processor\\CommandProcessor'] = new \PrestaShopBundle\ApiPlatform\Processor\CommandProcessor($a, ($container->privates['PrestaShopBundle\\ApiPlatform\\Serializer\\DomainSerializer'] ?? $container->load('getDomainSerializerService')), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\ShopContext'] ?? $container->load('getShopContextService')), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\LanguageContext'] ?? self::getLanguageContextService($container)), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\ApiClientContext'] ?? $container->load('getApiClientContextService')));
    }
}
