<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarrierControllerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShopBundle\Controller\Admin\Improve\Shipping\CarrierController' shared autowired service.
     *
     * @return \PrestaShopBundle\Controller\Admin\Improve\Shipping\CarrierController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['PrestaShopBundle\\Controller\\Admin\\Improve\\Shipping\\CarrierController'] = $instance = new \PrestaShopBundle\Controller\Admin\Improve\Shipping\CarrierController();

        $instance->setContainer(($container->privates['.service_locator.WuM.5MR'] ?? $container->load('get_ServiceLocator_WuM_5MRService'))->withContext('PrestaShopBundle\\Controller\\Admin\\Improve\\Shipping\\CarrierController', $container));

        return $instance;
    }
}
