<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeeFilters2Service extends AdminKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.rY3E3ag.PrestaShop\PrestaShop\Core\Search\Filters\Security\Session\EmployeeFilters' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Search\Filters\Security\Session\EmployeeFilters
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.rY3E3ag": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\Security\\Session\\EmployeeFilters" but no such service exists.');
    }
}
