<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExportThemeCommandService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShopBundle\Command\ExportThemeCommand' shared service.
     *
     * @return \PrestaShopBundle\Command\ExportThemeCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShopBundle\\Command\\ExportThemeCommand'] = new \PrestaShopBundle\Command\ExportThemeCommand(($container->services['prestashop.core.addon.theme.repository'] ?? $container->load('getPrestashop_Core_Addon_Theme_RepositoryService')), ($container->services['prestashop.core.addon.theme.exporter'] ?? $container->load('getPrestashop_Core_Addon_Theme_ExporterService')), ($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
