<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLegacyControllerContextService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShop\PrestaShop\Core\Context\LegacyControllerContext' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Core\Context\LegacyControllerContext
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['PrestaShop\\PrestaShop\\Core\\Context\\LegacyControllerContext'] = $container->createProxy('LegacyControllerContextProxy8391cd6', static fn () => \LegacyControllerContextProxy8391cd6::createLazyProxy(static fn () => self::do($container, false)));
        }

        return ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\LegacyControllerContextBuilder'] ?? self::getLegacyControllerContextBuilderService($container))->build();
    }
}
