<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLegacySessionAlertService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopBundle\Twig\Component\Legacy\LegacySessionAlert' autowired service.
     *
     * @return \PrestaShopBundle\Twig\Component\Legacy\LegacySessionAlert
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->factories['service_container']['PrestaShopBundle\\Twig\\Component\\Legacy\\LegacySessionAlert'] = function ($container) {
            return new \PrestaShopBundle\Twig\Component\Legacy\LegacySessionAlert(($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['translator'] ?? self::getTranslatorService($container)), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\ShopContext'] ?? $container->load('getShopContextService')));
        };

        return $container->factories['service_container']['PrestaShopBundle\\Twig\\Component\\Legacy\\LegacySessionAlert']($container);
    }
}
