<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLinkBlockControllerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShop\Module\LinkList\Controller\Admin\Improve\Design\LinkBlockController' shared autowired service.
     *
     * @return \PrestaShop\Module\LinkList\Controller\Admin\Improve\Design\LinkBlockController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['PrestaShop\\Module\\LinkList\\Controller\\Admin\\Improve\\Design\\LinkBlockController'] = $instance = new \PrestaShop\Module\LinkList\Controller\Admin\Improve\Design\LinkBlockController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('PrestaShop\\Module\\LinkList\\Controller\\Admin\\Improve\\Design\\LinkBlockController', $container));

        return $instance;
    }
}
