<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMenuBuilderService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopBundle\Twig\Layout\MenuBuilder' shared autowired service.
     *
     * @return \PrestaShopBundle\Twig\Layout\MenuBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['prestashop.router'] ?? $container->load('getPrestashop_RouterService'));

        if (isset($container->privates['PrestaShopBundle\\Twig\\Layout\\MenuBuilder'])) {
            return $container->privates['PrestaShopBundle\\Twig\\Layout\\MenuBuilder'];
        }

        return $container->privates['PrestaShopBundle\\Twig\\Layout\\MenuBuilder'] = new \PrestaShopBundle\Twig\Layout\MenuBuilder(($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['.container.private.prestashop.core.admin.tab.repository'] ?? self::get_Container_Private_Prestashop_Core_Admin_Tab_RepositoryService($container)), ($container->services['translator'] ?? self::getTranslatorService($container)), $a, ($container->services['.container.private.prestashop.bundle.routing.converter.legacy_parameters_converter'] ??= new \PrestaShopBundle\Routing\Converter\LegacyParametersConverter()));
    }
}
