<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMultistoreHeaderService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopBundle\Twig\Component\MultistoreHeader' autowired service.
     *
     * @return \PrestaShopBundle\Twig\Component\MultistoreHeader
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->factories['service_container']['PrestaShopBundle\\Twig\\Component\\MultistoreHeader'] = function ($container) {
            return new \PrestaShopBundle\Twig\Component\MultistoreHeader(($container->services['PrestaShop\\PrestaShop\\Adapter\\Feature\\MultistoreFeature'] ?? self::getMultistoreFeatureService($container)), ($container->services['PrestaShop\\PrestaShop\\Core\\Util\\ColorBrightnessCalculator'] ??= new \PrestaShop\PrestaShop\Core\Util\ColorBrightnessCalculator()), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container)), ($container->services['translator'] ?? self::getTranslatorService($container)), ($container->privates['PrestaShopBundle\\Twig\\Layout\\MenuBuilder'] ?? $container->load('getMenuBuilderService')), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\ShopContext'] ?? $container->load('getShopContextService')), $container->parameters['prestashop.controllers_all_shop_context']);
        };

        return $container->factories['service_container']['PrestaShopBundle\\Twig\\Component\\MultistoreHeader']($container);
    }
}
