<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_Hook_Provider_GridDefinitionHookByServiceIdsProviderService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.core.hook.provider.grid_definition_hook_by_service_ids_provider' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Hook\Provider\GridDefinitionHookByServiceIdsProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.core.hook.provider.grid_definition_hook_by_service_ids_provider'] = new \PrestaShop\PrestaShop\Core\Hook\Provider\GridDefinitionHookByServiceIdsProvider($container);
    }
}
