<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Module_LinkBlock_Grid_FactoryService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.module.link_block.grid.factory' shared service.
     *
     * @return \PrestaShop\Module\LinkList\Core\Grid\LinkBlockGridFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.module.link_block.grid.factory'] = new \PrestaShop\Module\LinkList\Core\Grid\LinkBlockGridFactory(($container->services['translator'] ?? self::getTranslatorService($container)), ($container->services['prestashop.module.link_block.grid.data_factory'] ?? $container->load('getPrestashop_Module_LinkBlock_Grid_DataFactoryService')), ($container->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? self::getHookDispatcherService($container)), ($container->services['prestashop.core.grid.filter.form_factory'] ?? $container->load('getPrestashop_Core_Grid_Filter_FormFactoryService')), ($container->services['.container.private.prestashop.adapter.shop.context'] ??= new \PrestaShop\PrestaShop\Adapter\Shop\Context()));
    }
}
