<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Presenter_Module_PaymentService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.presenter.module.payment' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Presenter\Module\PaymentModulesPresenter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.presenter.module.payment'] = new \PrestaShop\PrestaShop\Adapter\Presenter\Module\PaymentModulesPresenter(($container->services['prestashop.adapter.presenter.module'] ?? $container->load('getPrestashop_Adapter_Presenter_ModuleService')), ($container->services['prestashop.adapter.module.payment_module_provider'] ?? $container->load('getPrestashop_Adapter_Module_PaymentModuleProviderService')));
    }
}
