<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Category_CommandHandler_DeleteCategoryCoverImageHandlerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.category.command_handler.delete_category_cover_image_handler' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Category\CommandHandler\DeleteCategoryCoverImageHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.category.command_handler.delete_category_cover_image_handler'] = new \PrestaShop\PrestaShop\Adapter\Category\CommandHandler\DeleteCategoryCoverImageHandler(($container->privates['filesystem'] ??= new \Symfony\Component\Filesystem\Filesystem()), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration()));
    }
}
