<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Module_LinkBlock_CustomUrlTypeService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.module.link_block.custom_url_type' shared autowired service.
     *
     * @return \PrestaShop\Module\LinkList\Form\Type\CustomUrlType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.module.link_block.custom_url_type'] = new \PrestaShop\Module\LinkList\Form\Type\CustomUrlType(($container->services['translator'] ?? self::getTranslatorService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container))->getLanguages());
    }
}
