<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Presenter_ModuleService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.presenter.module' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Presenter\Module\ModulePresenter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.presenter.module'] = new \PrestaShop\PrestaShop\Adapter\Presenter\Module\ModulePresenter(($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container))->getContext()->currency, ($container->services['prestashop.adapter.formatter.price'] ??= new \PrestaShop\PrestaShop\Adapter\Product\PriceFormatter()));
    }
}
