<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_CheckMissingFilesService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.check_missing_files' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Requirement\CheckMissingOrUpdatedFiles
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.check_missing_files'] = new \PrestaShop\PrestaShop\Adapter\Requirement\CheckMissingOrUpdatedFiles();
    }
}
