<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_Localization_Currency_PatternTransformerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.core.localization.currency.pattern_transformer' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Localization\Currency\PatternTransformer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.core.localization.currency.pattern_transformer'] = new \PrestaShop\PrestaShop\Core\Localization\Currency\PatternTransformer();
    }
}
