<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Default_Language_ContextService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'prestashop.default.language.context' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Core\Context\LanguageContext
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['prestashop.default.language.context'] = $container->createProxy('LanguageContextProxyD23999d', static fn () => \LanguageContextProxyD23999d::createLazyProxy(static fn () => self::do($container, false)));
        }

        return ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\LanguageContextBuilder'] ?? self::getLanguageContextBuilderService($container))->buildDefault();
    }
}
