<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Admin_ProductPreferences_General_FormHandlerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.admin.product_preferences.general.form_handler' shared service.
     *
     * @return \PrestaShopBundle\Form\Admin\Configure\ShopParameters\ProductPreferences\ProductPreferencesFormHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['prestashop.admin.product_preferences.general.form_handler'] = $instance = new \PrestaShopBundle\Form\Admin\Configure\ShopParameters\ProductPreferences\ProductPreferencesFormHandler(($container->privates['form.factory'] ?? $container->load('getForm_FactoryService')), ($container->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? self::getHookDispatcherService($container)), ($container->services['prestashop.admin.product_preferences.general.data_provider'] ?? $container->load('getPrestashop_Admin_ProductPreferences_General_DataProviderService')), 'PrestaShopBundle\\Form\\Admin\\Configure\\ShopParameters\\ProductPreferences\\GeneralType', 'ProductPreferencesPageGeneral', 'general');

        $instance->setCacheClearer(($container->services['prestashop.core.cache.clearer.product_cache_clearer_chain'] ?? $container->load('getPrestashop_Core_Cache_Clearer_ProductCacheClearerChainService')));

        return $instance;
    }
}
