<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Cache_RefreshService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.cache.refresh' shared service.
     *
     * @return \PrestaShopBundle\Service\Cache\Refresh
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['prestashop.cache.refresh'] = $instance = new \PrestaShopBundle\Service\Cache\Refresh(($container->services['kernel'] ?? $container->get('kernel', 1)));

        $instance->addCacheClear();

        return $instance;
    }
}
