<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Language_Rtl_InstalledLanguageCheckerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.language.rtl.installed_language_checker' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Language\RTL\InstalledLanguageChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.language.rtl.installed_language_checker'] = new \PrestaShop\PrestaShop\Adapter\Language\RTL\InstalledLanguageChecker(($container->services['prestashop.adapter.data_provider.language'] ??= new \PrestaShop\PrestaShop\Adapter\Language\LanguageDataProvider()));
    }
}
