<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_File_RobotsTextFileGeneratorService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.file.robots_text_file_generator' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\File\RobotsTextFileGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.file.robots_text_file_generator'] = new \PrestaShop\PrestaShop\Adapter\File\RobotsTextFileGenerator();
    }
}
