<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Module_CommandHandler_BulkToggleModuleStatusHandlerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.module.command_handler.bulk_toggle_module_status_handler' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Module\CommandHandler\BulkToggleModuleStatusHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['PrestaShop\\PrestaShop\\Core\\Module\\ModuleManager'] ?? $container->load('getModuleManagerService'));

        if (isset($container->services['prestashop.adapter.module.command_handler.bulk_toggle_module_status_handler'])) {
            return $container->services['prestashop.adapter.module.command_handler.bulk_toggle_module_status_handler'];
        }

        return $container->services['prestashop.adapter.module.command_handler.bulk_toggle_module_status_handler'] = new \PrestaShop\PrestaShop\Adapter\Module\CommandHandler\BulkToggleModuleStatusHandler($a, ($container->services['prestashop.adapter.legacy.logger'] ??= new \PrestaShop\PrestaShop\Adapter\LegacyLogger()), ($container->services['prestashop.core.cache.clearer.cache_clearer_chain'] ?? $container->load('getPrestashop_Core_Cache_Clearer_CacheClearerChainService')));
    }
}
