<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_Grid_Factory_TaxRuleService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.core.grid.factory.tax_rule' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Grid\GridFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? self::getHookDispatcherService($container));

        $b = new \PrestaShop\PrestaShop\Core\Grid\Definition\Factory\TaxRuleGridDefinitionFactory($a);
        $b->setTranslator(($container->services['translator'] ?? self::getTranslatorService($container)));

        return $container->services['prestashop.core.grid.factory.tax_rule'] = new \PrestaShop\PrestaShop\Core\Grid\GridFactory($b, ($container->services['PrestaShop\\PrestaShop\\Core\\Grid\\Data\\Factory\\TaxRuleGridDataFactory'] ?? $container->load('getTaxRuleGridDataFactoryService')), ($container->services['prestashop.core.grid.filter.form_factory'] ?? $container->load('getPrestashop_Core_Grid_Filter_FormFactoryService')), $a);
    }
}
