<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Meta_MetaEraserService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.meta.meta_eraser' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Meta\MetaEraser
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.meta.meta_eraser'] = new \PrestaShop\PrestaShop\Adapter\Meta\MetaEraser();
    }
}
