<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQueryListProviderService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopBundle\ApiPlatform\Provider\QueryListProvider' shared autowired service.
     *
     * @return \PrestaShopBundle\ApiPlatform\Provider\QueryListProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['prestashop.core.api.search.builder'] ?? $container->load('getPrestashop_Core_Api_Search_BuilderService'));

        if (isset($container->privates['PrestaShopBundle\\ApiPlatform\\Provider\\QueryListProvider'])) {
            return $container->privates['PrestaShopBundle\\ApiPlatform\\Provider\\QueryListProvider'];
        }

        return $container->privates['PrestaShopBundle\\ApiPlatform\\Provider\\QueryListProvider'] = new \PrestaShopBundle\ApiPlatform\Provider\QueryListProvider(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['PrestaShopBundle\\ApiPlatform\\Serializer\\DomainSerializer'] ?? $container->load('getDomainSerializerService')), $container, ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\ShopContext'] ?? $container->load('getShopContextService')), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\LanguageContext'] ?? self::getLanguageContextService($container)), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\ApiClientContext'] ?? $container->load('getApiClientContextService')), $a);
    }
}
