<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSupplierFiltersService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.EB8Uo7V.PrestaShop\PrestaShop\Core\Search\Filters\SupplierFilters' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Search\Filters\SupplierFilters
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.EB8Uo7V": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\SupplierFilters" but no such service exists.');
    }
}
