<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_CacheWarmer_ExpressionService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'security.cache_warmer.expression' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\CacheWarmer\ExpressionCacheWarmer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['security.cache_warmer.expression'] = new \Symfony\Bundle\SecurityBundle\CacheWarmer\ExpressionCacheWarmer(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.security.expression.KpAzLuJ'] ??= new \Symfony\Component\ExpressionLanguage\Expression('request.attributes.has("_legacy_controller_anonymous") and request.attributes.get("_legacy_controller_anonymous") == true'));
        }, 1), ($container->privates['security.expression_language'] ?? self::getSecurity_ExpressionLanguageService($container)));
    }
}
