<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStoreFiltersService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.tSkqa9L.PrestaShop\PrestaShop\Core\Search\Filters\StoreFilters' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Search\Filters\StoreFilters
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.tSkqa9L": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\StoreFilters" but no such service exists.');
    }
}
