<?php

namespace Container80LivO1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTemplateVariablesService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopBundle\Twig\Layout\TemplateVariables' shared autowired service.
     *
     * @return \PrestaShopBundle\Twig\Layout\TemplateVariables
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['PrestaShopBundle\\Twig\\Layout\\TemplateVariables'] = $container->createProxy('TemplateVariablesProxy150279b', static fn () => \TemplateVariablesProxy150279b::createLazyProxy(static fn () => self::do($container, false)));
        }

        return (new \PrestaShopBundle\Twig\Layout\TemplateVariablesBuilder(($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container)), false, ($container->services['PrestaShopBundle\\Security\\Admin\\UserTokenManager'] ?? self::getUserTokenManagerService($container)), '9.0.0', ($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration()), ($container->privates['PrestaShopBundle\\Twig\\Layout\\MenuBuilder'] ?? $container->load('getMenuBuilderService')), ($container->services['.container.private.prestashop.core.admin.tab.repository'] ?? self::get_Container_Private_Prestashop_Core_Admin_Tab_RepositoryService($container)), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\EmployeeContext'] ?? self::getEmployeeContextService($container)), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\LanguageContext'] ?? self::getLanguageContextService($container)), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\ShopContext'] ?? $container->load('getShopContextService')), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\LegacyControllerContext'] ?? $container->load('getLegacyControllerContextService')), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Feature\\MultistoreFeature'] ?? self::getMultistoreFeatureService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack())))->build();
    }
}
