<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DDfSQE_Service extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.DDfSQE.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DDfSQE.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'filters' => ['privates', '.errored..service_locator.DDfSQE..PrestaShop\\PrestaShop\\Core\\Search\\Filters\\StateFilters', NULL, 'Cannot autowire service ".service_locator.DDfSQE.": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\StateFilters" but no such service exists.'],
        ], [
            'filters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\StateFilters',
        ]);
    }
}
