<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_By2HUDZService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.by2HUDZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.by2HUDZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cartRuleFilters' => ['privates', '.errored..service_locator.by2HUDZ.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CartRuleFilters', NULL, 'Cannot autowire service ".service_locator.by2HUDZ": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CartRuleFilters" but no such service exists.'],
        ], [
            'cartRuleFilters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CartRuleFilters',
        ]);
    }
}
