<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_ZaWinUyService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.ZaWinUy' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.ZaWinUy'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor((new \PrestaShop\PrestaShop\Adapter\Alias\CommandHandler\UpdateAliasStatusHandler(($container->privates['PrestaShop\\PrestaShop\\Adapter\\Alias\\Repository\\AliasRepository'] ?? $container->load('getAliasRepositoryService'))))->handle(...), ['method' => 'handle']);
    }
}
