<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WuM_5MRService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.WuM.5MR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WuM.5MR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'PrestaShopBundle\\Service\\Grid\\ResponseBuilder' => ['services', '.container.private.prestashop.bundle.grid.response_builder', 'get_Container_Private_Prestashop_Bundle_Grid_ResponseBuilderService', true],
            'PrestaShop\\PrestaShop\\Core\\CommandBus\\CommandBusInterface' => ['services', 'prestashop.core.command_bus', 'getPrestashop_Core_CommandBusService', true],
            'PrestaShop\\PrestaShop\\Core\\ConfigurationInterface' => ['services', 'PrestaShop\\PrestaShop\\Adapter\\Configuration', 'getConfigurationService', false],
            'PrestaShop\\PrestaShop\\Core\\Context\\LanguageContext' => ['privates', 'PrestaShop\\PrestaShop\\Core\\Context\\LanguageContext', 'getLanguageContextService', false],
            'PrestaShop\\PrestaShop\\Core\\Grid\\Position\\GridPositionUpdaterInterface' => ['services', 'PrestaShop\\PrestaShop\\Core\\Grid\\Position\\GridPositionUpdater', 'getGridPositionUpdaterService', true],
            'PrestaShop\\PrestaShop\\Core\\Grid\\Position\\PositionUpdateFactoryInterface' => ['services', 'PrestaShop\\PrestaShop\\Core\\Grid\\Position\\PositionUpdateFactory', 'getPositionUpdateFactoryService', true],
            'PrestaShop\\PrestaShop\\Core\\Grid\\Presenter\\GridPresenterInterface' => ['services', '.container.private.prestashop.core.grid.presenter.grid_presenter', 'get_Container_Private_Prestashop_Core_Grid_Presenter_GridPresenterService', true],
            'PrestaShop\\PrestaShop\\Core\\Help\\Documentation' => ['services', 'PrestaShop\\PrestaShop\\Core\\Help\\Documentation', 'getDocumentationService', true],
            'PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcherInterface' => ['services', 'PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher', 'getHookDispatcherService', false],
            'Symfony\\Contracts\\Translation\\TranslatorInterface' => ['services', 'translator', 'getTranslatorService', false],
            'form.factory' => ['privates', 'form.factory', 'getForm_FactoryService', true],
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'router' => ['services', 'prestashop.router', 'getPrestashop_RouterService', true],
            'security.authorization_checker' => ['privates', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
            'security.csrf.token_manager' => ['services', 'Symfony\\Component\\Security\\Csrf\\CsrfTokenManagerInterface', 'getCsrfTokenManagerInterfaceService', false],
            'security.token_storage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
            'twig' => ['privates', 'twig', 'getTwigService', true],
            'web_link.http_header_serializer' => ['privates', 'web_link.http_header_serializer', 'getWebLink_HttpHeaderSerializerService', false],
        ], [
            'PrestaShopBundle\\Service\\Grid\\ResponseBuilder' => '?',
            'PrestaShop\\PrestaShop\\Core\\CommandBus\\CommandBusInterface' => '?',
            'PrestaShop\\PrestaShop\\Core\\ConfigurationInterface' => '?',
            'PrestaShop\\PrestaShop\\Core\\Context\\LanguageContext' => 'PrestaShop\\PrestaShop\\Core\\Context\\LanguageContext',
            'PrestaShop\\PrestaShop\\Core\\Grid\\Position\\GridPositionUpdaterInterface' => '?',
            'PrestaShop\\PrestaShop\\Core\\Grid\\Position\\PositionUpdateFactoryInterface' => '?',
            'PrestaShop\\PrestaShop\\Core\\Grid\\Presenter\\GridPresenterInterface' => '?',
            'PrestaShop\\PrestaShop\\Core\\Help\\Documentation' => 'PrestaShop\\PrestaShop\\Core\\Help\\Documentation',
            'PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcherInterface' => '?',
            'Symfony\\Contracts\\Translation\\TranslatorInterface' => '?',
            'form.factory' => '?',
            'http_kernel' => '?',
            'parameter_bag' => '?',
            'request_stack' => '?',
            'router' => '?',
            'security.authorization_checker' => '?',
            'security.csrf.token_manager' => '?',
            'security.token_storage' => '?',
            'serializer' => '?',
            'twig' => '?',
            'web_link.http_header_serializer' => '?',
        ]);
    }
}
