<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_HwqY9yeService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.HwqY9ye' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['prestashop.adapter.module.command_handler.bulk_toggle_module_status_handler'] ?? $container->load('getPrestashop_Adapter_Module_CommandHandler_BulkToggleModuleStatusHandlerService'));

        if (isset($container->privates['.messenger.handler_descriptor.HwqY9ye'])) {
            return $container->privates['.messenger.handler_descriptor.HwqY9ye'];
        }

        return $container->privates['.messenger.handler_descriptor.HwqY9ye'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor($a->handle(...), ['method' => 'handle']);
    }
}
