<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F2hDrZKService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.F2hDrZK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F2hDrZK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'zoneFilters' => ['privates', '.errored..service_locator.F2hDrZK.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ZoneFilters', NULL, 'Cannot autowire service ".service_locator.F2hDrZK": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ZoneFilters" but no such service exists.'],
        ], [
            'zoneFilters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\ZoneFilters',
        ]);
    }
}
