<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R3qk0roService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.R3qk0ro' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.R3qk0ro'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'attributeFilters' => ['privates', '.errored..service_locator.R3qk0ro.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\AttributeFilters', NULL, 'Cannot autowire service ".service_locator.R3qk0ro": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\AttributeFilters" but no such service exists.'],
        ], [
            'attributeFilters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\AttributeFilters',
        ]);
    }
}
