<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Container_Private_Prestashop_Bundle_Twig_Extension_ColumnService extends AdminKernelProdContainer
{
    /*
     * Gets the public '.container.private.prestashop.bundle.twig.extension.column' shared autowired service.
     *
     * @return \PrestaShopBundle\Twig\Extension\GridExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['twig'] ?? $container->load('getTwigService'));

        if (isset($container->services['.container.private.prestashop.bundle.twig.extension.column'])) {
            return $container->services['.container.private.prestashop.bundle.twig.extension.column'];
        }

        return $container->services['.container.private.prestashop.bundle.twig.extension.column'] = new \PrestaShopBundle\Twig\Extension\GridExtension($a, ($container->services['prestashop.static_cache.adapter'] ?? $container->load('getPrestashop_StaticCache_AdapterService')));
    }
}
