<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_UxIcons_IconFinderService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.ux_icons.icon_finder' shared service.
     *
     * @return \Symfony\UX\Icons\Twig\IconFinder
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.ux_icons.icon_finder'] = new \Symfony\UX\Icons\Twig\IconFinder(($container->privates['twig'] ?? $container->load('getTwigService')), (\dirname(__DIR__, 5).'/admin772pquvgjklwjqimfqv/themes/new-theme/icons'));
    }
}
