<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FCBHOzService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.FC_bHOz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FC_bHOz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kpiRow' => ['privates', '.errored..service_locator.FC_bHOz.PrestaShop\\PrestaShop\\Core\\Kpi\\Row\\KpiRowInterface', NULL, 'Cannot autowire service ".service_locator.FC_bHOz": it references interface "PrestaShop\\PrestaShop\\Core\\Kpi\\Row\\KpiRowInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'kpiRow' => 'PrestaShop\\PrestaShop\\Core\\Kpi\\Row\\KpiRowInterface',
        ]);
    }
}
