<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BmorfB9Service extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.bmorfB9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bmorfB9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'filters' => ['privates', '.errored..service_locator.bmorfB9.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CustomerFilters', NULL, 'Cannot autowire service ".service_locator.bmorfB9": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CustomerFilters" but no such service exists.'],
        ], [
            'filters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CustomerFilters',
        ]);
    }
}
