<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RZgq9cEService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.service_locator.RZgq9cE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RZgq9cE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'catalogPriceRuleFilters' => ['privates', '.errored..service_locator.RZgq9cE.PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CatalogPriceRuleFilters', NULL, 'Cannot autowire service ".service_locator.RZgq9cE": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CatalogPriceRuleFilters" but no such service exists.'],
        ], [
            'catalogPriceRuleFilters' => 'PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CatalogPriceRuleFilters',
        ]);
    }
}
