<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiClientRepositoryService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShopBundle\Entity\Repository\ApiClientRepository' shared service.
     *
     * @return \PrestaShopBundle\Entity\Repository\ApiClientRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['PrestaShopBundle\\Entity\\Repository\\ApiClientRepository'] = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container))->getRepository('PrestaShopBundle\\Entity\\ApiClient');
    }
}
