<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssets_VersionDefaultService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'assets._version__default' shared service.
     *
     * @return \Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['assets._version__default'] = new \Symfony\Component\Asset\VersionStrategy\StaticVersionStrategy('9.0.0', '%s?%s');
    }
}
