<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCurrencyContextService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShop\PrestaShop\Core\Context\CurrencyContext' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Core\Context\CurrencyContext
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['PrestaShop\\PrestaShop\\Core\\Context\\CurrencyContext'] = $container->createProxy('CurrencyContextProxy732debc', static fn () => \CurrencyContextProxy732debc::createLazyProxy(static fn () => self::do($container, false)));
        }

        return ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\CurrencyContextBuilder'] ?? self::getCurrencyContextBuilderService($container))->build();
    }
}
