<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCurrencyFiltersService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.gXU0rXB.PrestaShop\PrestaShop\Core\Search\Filters\CurrencyFilters' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Search\Filters\CurrencyFilters
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.gXU0rXB": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\CurrencyFilters" but no such service exists.');
    }
}
