<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDomainSerializerService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopBundle\ApiPlatform\Serializer\DomainSerializer' shared service.
     *
     * @return \PrestaShopBundle\ApiPlatform\Serializer\DomainSerializer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PrestaShopBundle\\ApiPlatform\\Serializer\\DomainSerializer'] = new \PrestaShopBundle\ApiPlatform\Serializer\DomainSerializer(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['PrestaShopBundle\\ApiPlatform\\Normalizer\\DateTimeImmutableNormalizer'] ??= new \PrestaShopBundle\ApiPlatform\Normalizer\DateTimeImmutableNormalizer());
            yield 1 => ($container->privates['PrestaShopBundle\\ApiPlatform\\Normalizer\\DecimalNumberNormalizer'] ??= new \PrestaShopBundle\ApiPlatform\Normalizer\DecimalNumberNormalizer());
            yield 2 => ($container->privates['PrestaShopBundle\\ApiPlatform\\Normalizer\\ShopConstraintNormalizer'] ??= new \PrestaShopBundle\ApiPlatform\Normalizer\ShopConstraintNormalizer());
            yield 3 => ($container->privates['PrestaShopBundle\\ApiPlatform\\Normalizer\\UploadedFileNormalizer'] ??= new \PrestaShopBundle\ApiPlatform\Normalizer\UploadedFileNormalizer());
            yield 4 => ($container->privates['PrestaShopBundle\\ApiPlatform\\Normalizer\\CQRSApiNormalizer'] ??= new \PrestaShopBundle\ApiPlatform\Normalizer\CQRSApiNormalizer());
        }, 5));
    }
}
