<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeePasswordResetterService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShopBundle\Security\Admin\EmployeePasswordResetter' shared autowired service.
     *
     * @return \PrestaShopBundle\Security\Admin\EmployeePasswordResetter
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->services['PrestaShopBundle\\Security\\Admin\\EmployeePasswordResetter'] = $container->createProxy('EmployeePasswordResetterGhost6167120', static fn () => \EmployeePasswordResetterGhost6167120::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        return ($lazyLoad->__construct(($container->services['PrestaShopBundle\\Entity\\Repository\\EmployeeRepository'] ?? self::getEmployeeRepositoryService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration()), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['prestashop.router'] ?? $container->load('getPrestashop_RouterService')), ($container->services['translator'] ?? self::getTranslatorService($container)), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\ShopContext'] ?? $container->load('getShopContextService')), ($container->services['hashing'] ??= new \PrestaShop\PrestaShop\Core\Crypto\Hashing()), 'stI2AkApLnErV81VHFnDtfKiGcf5jNCLj2VQinm8aeLXfny8B8c5gLN6GbpRnL84') && false ?: $lazyLoad);
    }
}
