<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLegacyNavBarService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopBundle\Twig\Component\Legacy\LegacyNavBar' autowired service.
     *
     * @return \PrestaShopBundle\Twig\Component\Legacy\LegacyNavBar
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->factories['service_container']['PrestaShopBundle\\Twig\\Component\\Legacy\\LegacyNavBar'] = function ($container) {
            return new \PrestaShopBundle\Twig\Component\Legacy\LegacyNavBar(($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container)), ($container->services['logger'] ?? self::getLoggerService($container)), ($container->privates['PrestaShopBundle\\Twig\\Layout\\MenuBuilder'] ?? $container->load('getMenuBuilderService')), '9.0.0');
        };

        return $container->factories['service_container']['PrestaShopBundle\\Twig\\Component\\Legacy\\LegacyNavBar']($container);
    }
}
