<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMobileQuickAccessService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopBundle\Twig\Component\MobileQuickAccess' autowired service.
     *
     * @return \PrestaShopBundle\Twig\Component\MobileQuickAccess
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->factories['service_container']['PrestaShopBundle\\Twig\\Component\\MobileQuickAccess'] = function ($container) {
            return new \PrestaShopBundle\Twig\Component\MobileQuickAccess(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['PrestaShopBundle\\Twig\\Layout\\MenuBuilder'] ?? $container->load('getMenuBuilderService')), ($container->services['PrestaShop\\PrestaShop\\Core\\QuickAccess\\QuickAccessGenerator'] ?? $container->load('getQuickAccessGeneratorService')));
        };

        return $container->factories['service_container']['PrestaShopBundle\\Twig\\Component\\MobileQuickAccess']($container);
    }
}
