<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModuleRepositoryService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShop\PrestaShop\Core\Module\ModuleRepository' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Module\ModuleRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->services['PrestaShop\\PrestaShop\\Core\\Module\\ModuleRepository'] = $container->createProxy('ModuleRepositoryGhostE5bd087', static fn () => \ModuleRepositoryGhostE5bd087::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        return ($lazyLoad->__construct(($container->services['prestashop.adapter.data_provider.module'] ?? $container->load('getPrestashop_Adapter_DataProvider_ModuleService')), ($container->services['prestashop.core.admin.data_provider.module_interface'] ?? $container->load('getPrestashop_Core_Admin_DataProvider_ModuleInterfaceService')), ($container->services['doctrine.cache.provider'] ?? $container->load('getDoctrine_Cache_ProviderService')), ($container->services['PrestaShop\\PrestaShop\\Adapter\\HookManager'] ??= new \PrestaShop\PrestaShop\Adapter\HookManager()), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration())->get("_PS_MODULE_DIR_"), ($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container))->getContext()->language->id) && false ?: $lazyLoad);
    }
}
