<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNoQtyProductWithoutCombinationFiltersService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator._Gl1WsZ.PrestaShop\PrestaShop\Core\Search\Filters\Monitoring\NoQtyProductWithoutCombinationFilters' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Search\Filters\Monitoring\NoQtyProductWithoutCombinationFilters
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator._Gl1WsZ": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\Monitoring\\NoQtyProductWithoutCombinationFilters" but no such service exists.');
    }
}
