<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderReturnStatesFiltersService extends AdminKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.MZbFnJg.PrestaShop\PrestaShop\Core\Search\Filters\OrderReturnStatesFilters' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Search\Filters\OrderReturnStatesFilters
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.MZbFnJg": it references class "PrestaShop\\PrestaShop\\Core\\Search\\Filters\\OrderReturnStatesFilters" but no such service exists.');
    }
}
