<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_MailTemplate_PreviewVariablesBuilderService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.mail_template.preview_variables_builder' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\MailTemplate\MailPreviewVariablesBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.mail_template.preview_variables_builder'] = new \PrestaShop\PrestaShop\Adapter\MailTemplate\MailPreviewVariablesBuilder(($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration()), ($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container)), ($container->services['prestashop.adapter.data_provider.employee'] ?? $container->load('getPrestashop_Adapter_DataProvider_EmployeeService')), ($container->services['prestashop.adapter.mail_template.partial_template_renderer'] ?? $container->load('getPrestashop_Adapter_MailTemplate_PartialTemplateRendererService')), ($container->services['prestashop.core.localization.locale.context_locale'] ?? $container->load('getPrestashop_Core_Localization_Locale_ContextLocaleService')), ($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
