<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Bundle_Grid_ControllerResponseBuilderService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.bundle.grid.controller_response_builder' shared service.
     *
     * @return \PrestaShopBundle\Service\Grid\ControllerResponseBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.bundle.grid.controller_response_builder'] = new \PrestaShopBundle\Service\Grid\ControllerResponseBuilder(($container->services['prestashop.core.grid.filter.form_factory'] ?? $container->load('getPrestashop_Core_Grid_Filter_FormFactoryService')), ($container->services['prestashop.router'] ?? $container->load('getPrestashop_RouterService')));
    }
}
