<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_Grid_Filter_MerchandiseReturnFormFactoryService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.core.grid.filter.merchandise_return_form_factory' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Grid\Filter\FilterFormFactoryFormActionDecorator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.core.grid.filter.merchandise_return_form_factory'] = new \PrestaShop\PrestaShop\Core\Grid\Filter\FilterFormFactoryFormActionDecorator(($container->services['prestashop.core.grid.filter.form_factory'] ?? $container->load('getPrestashop_Core_Grid_Filter_FormFactoryService')), ($container->services['prestashop.router'] ?? $container->load('getPrestashop_RouterService')), 'admin_merchandise_returns_filter');
    }
}
