<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Webservice_WebserviceKeyEraserService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.webservice.webservice_key_eraser' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Webservice\WebserviceKeyEraser
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.webservice.webservice_key_eraser'] = new \PrestaShop\PrestaShop\Adapter\Webservice\WebserviceKeyEraser();
    }
}
