<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_B2b_B2bFeatureService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.core.b2b.b2b_feature' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\B2b\B2bFeature
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.core.b2b.b2b_feature'] = new \PrestaShop\PrestaShop\Core\B2b\B2bFeature(($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration()));
    }
}
