<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Feature_FeatureService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.feature.feature' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Feature\FeatureFeature
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.feature.feature'] = new \PrestaShop\PrestaShop\Adapter\Feature\FeatureFeature(($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration()));
    }
}
