<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_MailTemplate_ThemeFolderCatalogService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.core.mail_template.theme_folder_catalog' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\MailTemplate\FolderThemeCatalog
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.core.mail_template.theme_folder_catalog'] = new \PrestaShop\PrestaShop\Core\MailTemplate\FolderThemeCatalog((\dirname(__DIR__, 5).'/mails/themes'), ($container->services['prestashop.core.mail_template.theme_folder_scanner'] ??= new \PrestaShop\PrestaShop\Core\MailTemplate\FolderThemeScanner()), ($container->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? self::getHookDispatcherService($container)));
    }
}
