<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_MailTemplate_GeneratorService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.core.mail_template.generator' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\MailTemplate\MailTemplateGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['prestashop.adapter.mail_template.twig_renderer'] ?? $container->load('getPrestashop_Adapter_MailTemplate_TwigRendererService'));

        if (isset($container->services['prestashop.core.mail_template.generator'])) {
            return $container->services['prestashop.core.mail_template.generator'];
        }

        return $container->services['prestashop.core.mail_template.generator'] = new \PrestaShop\PrestaShop\Core\MailTemplate\MailTemplateGenerator($a, ($container->services['logger'] ?? self::getLoggerService($container)));
    }
}
