<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_MailTemplate_TwigRendererService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.mail_template.twig_renderer' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\MailTemplate\MailTemplateTwigRenderer
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['twig'] ?? $container->load('getTwigService'));

        if (isset($container->services['prestashop.adapter.mail_template.twig_renderer'])) {
            return $container->services['prestashop.adapter.mail_template.twig_renderer'];
        }

        $container->services['prestashop.adapter.mail_template.twig_renderer'] = $instance = new \PrestaShop\PrestaShop\Adapter\MailTemplate\MailTemplateTwigRenderer($a, ($container->services['prestashop.core.mail_template.variables_builder'] ?? $container->load('getPrestashop_Core_MailTemplate_VariablesBuilderService')), ($container->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? self::getHookDispatcherService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration())->getBoolean("PS_GIFT_WRAPPING"));

        $instance->addTransformation(($container->services['prestashop.core.mail_template.transformation.css_inline'] ??= new \PrestaShop\PrestaShop\Core\MailTemplate\Transformation\CSSInlineTransformation()));
        $instance->addTransformation(($container->services['prestashop.core.mail_template.transformation.html_textify'] ??= new \PrestaShop\PrestaShop\Core\MailTemplate\Transformation\HTMLToTextTransformation()));

        return $instance;
    }
}
