<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_MailTemplate_CommandHandler_GenerateThemeMailsHandlerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.core.mail_template.command_handler.generate_theme_mails_handler' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Domain\MailTemplate\CommandHandler\GenerateThemeMailTemplatesHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['prestashop.core.mail_template.generator'] ?? $container->load('getPrestashop_Core_MailTemplate_GeneratorService'));

        if (isset($container->services['prestashop.core.mail_template.command_handler.generate_theme_mails_handler'])) {
            return $container->services['prestashop.core.mail_template.command_handler.generate_theme_mails_handler'];
        }

        return $container->services['prestashop.core.mail_template.command_handler.generate_theme_mails_handler'] = new \PrestaShop\PrestaShop\Core\Domain\MailTemplate\CommandHandler\GenerateThemeMailTemplatesHandler(($container->services['prestashop.core.admin.lang.repository'] ?? self::getPrestashop_Core_Admin_Lang_RepositoryService($container)), ($container->services['prestashop.core.mail_template.theme_folder_catalog'] ?? $container->load('getPrestashop_Core_MailTemplate_ThemeFolderCatalogService')), $a, (\dirname(__DIR__, 5).'/mails'), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration())->get("_PS_MODULE_DIR_"));
    }
}
