<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Module_LinkBlock_FormProviderService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.module.link_block.form_provider' shared service.
     *
     * @return \PrestaShop\Module\LinkList\Form\LinkBlockFormDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.module.link_block.form_provider'] = new \PrestaShop\Module\LinkList\Form\LinkBlockFormDataProvider(($container->services['prestashop.module.link_block.repository'] ?? $container->load('getPrestashop_Module_LinkBlock_RepositoryService')), ($container->services['prestashop.module.link_block.cache'] ??= new \PrestaShop\Module\LinkList\Cache\LegacyLinkBlockCache()), ($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container))->getLanguages(false, ($container->services['.container.private.prestashop.adapter.shop.context'] ??= new \PrestaShop\PrestaShop\Adapter\Shop\Context())->getContextShopID()), ($container->services['.container.private.prestashop.adapter.shop.context'] ??= new \PrestaShop\PrestaShop\Adapter\Shop\Context()), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration()));
    }
}
