<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_Addon_Theme_ExporterService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.core.addon.theme.exporter' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Addon\Theme\ThemeExporter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.core.addon.theme.exporter'] = new \PrestaShop\PrestaShop\Core\Addon\Theme\ThemeExporter(($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration()), ($container->privates['filesystem'] ??= new \Symfony\Component\Filesystem\Filesystem()), ($container->services['prestashop.core.admin.lang.repository'] ?? self::getPrestashop_Core_Admin_Lang_RepositoryService($container)), ($container->services['prestashop.translation.theme.exporter'] ?? $container->load('getPrestashop_Translation_Theme_ExporterService')));
    }
}
