<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Adapter_Group_GroupDataProviderService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.adapter.group.group_data_provider' shared service.
     *
     * @return \PrestaShop\PrestaShop\Adapter\Group\GroupDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.adapter.group.group_data_provider'] = new \PrestaShop\PrestaShop\Adapter\Group\GroupDataProvider();
    }
}
