<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_Grid_Filter_FormFactoryService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.core.grid.filter.form_factory' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Grid\Filter\GridFilterFormFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['form.factory'] ?? $container->load('getForm_FactoryService'));

        if (isset($container->services['prestashop.core.grid.filter.form_factory'])) {
            return $container->services['prestashop.core.grid.filter.form_factory'];
        }

        return $container->services['prestashop.core.grid.filter.form_factory'] = new \PrestaShop\PrestaShop\Core\Grid\Filter\GridFilterFormFactory($a, ($container->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? self::getHookDispatcherService($container)));
    }
}
