<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestashop_Core_KpiRow_PresenterService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'prestashop.core.kpi_row.presenter' shared service.
     *
     * @return \PrestaShop\PrestaShop\Core\Kpi\Row\KpiRowPresenter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['prestashop.core.kpi_row.presenter'] = new \PrestaShop\PrestaShop\Core\Kpi\Row\KpiRowPresenter();
    }
}
