<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSmartyVariablesFillerService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShopBundle\Twig\Layout\SmartyVariablesFiller' shared autowired service.
     *
     * @return \PrestaShopBundle\Twig\Layout\SmartyVariablesFiller
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['PrestaShopBundle\\Twig\\Layout\\SmartyVariablesFiller'] = new \PrestaShopBundle\Twig\Layout\SmartyVariablesFiller(($container->privates['PrestaShopBundle\\Twig\\Layout\\TemplateVariables'] ?? $container->load('getTemplateVariablesService')), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\LegacyControllerContext'] ?? $container->load('getLegacyControllerContextService')), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\LanguageContext'] ?? self::getLanguageContextService($container)), ($container->privates['prestashop.default.language.context'] ?? $container->load('getPrestashop_Default_Language_ContextService')), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\ShopContext'] ?? $container->load('getShopContextService')), ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\CountryContext'] ?? $container->load('getCountryContextService')), ($container->services['PrestaShop\\PrestaShop\\Adapter\\LegacyContext'] ?? self::getLegacyContextService($container)), ($container->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ??= new \PrestaShop\PrestaShop\Adapter\Configuration()));
    }
}
