<?php

namespace ContainerGqfUnWk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShopContextService extends AdminKernelProdContainer
{
    /*
     * Gets the private 'PrestaShop\PrestaShop\Core\Context\ShopContext' shared autowired service.
     *
     * @return \PrestaShop\PrestaShop\Core\Context\ShopContext
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['PrestaShop\\PrestaShop\\Core\\Context\\ShopContext'] = $container->createProxy('ShopContextProxy8518dfe', static fn () => \ShopContextProxy8518dfe::createLazyProxy(static fn () => self::do($container, false)));
        }

        return ($container->privates['PrestaShop\\PrestaShop\\Core\\Context\\ShopContextBuilder'] ?? self::getShopContextBuilderService($container))->build();
    }
}
