<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGqfUnWk\AdminKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGqfUnWk/AdminKernelProdContainer.php') {
    touch(__DIR__.'/ContainerGqfUnWk.legacy');

    return;
}

if (!\class_exists(AdminKernelProdContainer::class, false)) {
    \class_alias(\ContainerGqfUnWk\AdminKernelProdContainer::class, AdminKernelProdContainer::class, false);
}

return new \ContainerGqfUnWk\AdminKernelProdContainer([
    'container.build_hash' => 'GqfUnWk',
    'container.build_id' => '28a4886c',
    'container.build_time' => 1718222410,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGqfUnWk');
